name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- pygrib
- netCDF4
- pykdtree
- h5py
- xarray
- pip
- pip: 
  - cadati
  - requests
  - tqdm
  - lxml
  - pygeogrids>=0.3.0
  - pynetcf>=0.2.2
