name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- pygrib
- pykdtree
- h5py==3.6.0
- netCDF4
- pip
- pip:
  - cadati
  - xarray
  - requests
  - tqdm
  - lxml
  - pygeogrids>=0.3.0
  - pynetcf>=0.2.2
