name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- h5py
- netCDF4
- pykdtree
- pybufr-ecmwf
- pip
- pip: 
  - lxml
  - pygeobase>=0.4.0
  - pygeogrids>=0.3.0
  - pynetcf>=0.2.2
