name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- pygrib
- pykdtree
- pip
- pip: 
  - cadati
  - netCDF4
  - h5py
  - xarray
  - requests
  - tqdm
  - lxml
  - pygeogrids>=0.3.0
  - pynetcf>=0.2.2
