name: ascat_ubuntu
on: [push]

jobs:
    ascat_test:
        runs-on: ubuntu-latest
        steps:
        #checkout the repository
        - uses: actions/checkout@v2
        #install miniconda environment
        - uses: conda-incubator/setup-miniconda@v2
          with:
            miniconda-version: "latest"
            environment-file: tests/test_env.yml
            activate-environment: test_ascat
            show-channel-urls: true
            use-only-tar-bz2: true
            auto-activate-base: false
            auto-update-conda: true
        - run: |
            python -m pytest
