name: ascat_ubuntu
on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]

    name: ascat_test ${{ matrix.os }}  ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: tests/test_env.yml
          activate-environment: test_ascat

          miniconda-version: "latest"

          python-version: ${{matrix.python-version}}

          show-channel-urls: true
          use-only-tar-bz2: true

          auto-activate-base: false
          auto-update-conda: true


      - name: test ascat
        shell: bash -l {0}
        run: |
          python -m pytest
