name: windows

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: Build py${{ matrix.python-version }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ['windows-latest']
        ymlfile: ["environment_win.yml"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false # does not work with self-hosted testdata
      - name: Checkout test data
        shell: bash -l {0}
        run : |
          git submodule init
          git submodule sync
          git submodule update
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          miniforge-variant: Mambaforge
          miniforge-version: "latest"
          channel-priority: flexible
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.ymlfile }}
          activate-environment: ascat_env
          auto-activate-base: false
      - name: Print infos
        shell: bash -l {0}
        run: |
          git status
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Install package and test
        shell: bash -l {0}
        run: |
          pip install -e .[testing]
          pytest --cache-clear
